CREATE SCHEMA IF NOT EXISTS INTELAF;
USE INTELAF;

CREATE TABLE IF NOT EXISTS TIENDA(
codigo VARCHAR(45) NOT NULL,
nombre VARCHAR(45) NOT NULL,
direccion VARCHAR(45) NOT NULL,
telefono_1 VARCHAR(15) NOT NULL,
telefono_2 VARCHAR(15),
email VARCHAR(45),
horario VARCHAR(45),
PRIMARY KEY(codigo)
);

CREATE TABLE IF NOT EXISTS PRODUCTO(
codigo VARCHAR(45) NOT NULL,
nombre VARCHAR(45) NOT NULL,
fabricante VARCHAR(45) NOT NULL,
cantidad INT NOT NULL,
precio DOUBLE NOT NULL,
descripcion VARCHAR(200),
garantia INT,
codigo_tienda VARCHAR(45) NOT NULL,
PRIMARY KEY(codigo),
FOREIGN KEY(codigo_tienda) REFERENCES TIENDA(codigo)
);

CREATE TABLE IF NOT EXISTS CLIENTE(
NIT VARCHAR(13) NOT NULL,
nombre VARCHAR(45) NOT NULL,
telefono VARCHAR(45) NOT NULL,
DPI VARCHAR(13),
email VARCHAR(45),
direccion VARCHAR(45),
credito_compra DOUBLE,
PRIMARY KEY(NIT)
);

CREATE TABLE IF NOT EXISTS TIEMPO_DE_ENVIO(
ID INT NOT NULL AUTO_INCREMENT,
tiempo INT NOT NULL,
codigo_tienda1 VARCHAR(45) NOT NULL,
codigo_tienda2 VARCHAR(45) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(codigo_tienda1) REFERENCES TIENDA(codigo),
FOREIGN KEY(codigo_tienda2) REFERENCES TIENDA(codigo),
 CONSTRAINT tiempo_existente UNIQUE (codigo_tienda1,codigo_tienda2)
);

CREATE TABLE IF NOT EXISTS EMPLEADO(
codigo VARCHAR(45),
nombre VARCHAR(45) NOT NULL,
telefono VARCHAR(45) NOT NULL,
NIT VARCHAR(13),
DPI VARCHAR(13) NOT NULL,
email VARCHAR(45) NOT NULL,
direccion VARCHAR(45) NOT NULL,
PRIMARY KEY(codigo)
);

CREATE TABLE IF NOT EXISTS FACTURA(
codigo INT NOT NULL AUTO_INCREMENT,
fecha DATE NOT NULL,
total DOUBLE NOT NULL,
codigo_tienda VARCHAR(45) NOT NULL,
nit_cliente VARCHAR(13) NOT NULL,
PRIMARY KEY(codigo),
FOREIGN KEY(codigo_tienda) REFERENCES TIENDA(codigo),
FOREIGN KEY(nit_cliente) REFERENCES CLIENTE(NIT)
);

CREATE TABLE IF NOT EXISTS VENTA(
ID INT NOT NULL AUTO_INCREMENT,
precio DOUBLE NOT NULL,
cantidad INT NOT NULL,
codigo_producto VARCHAR(45) NOT NULL,
codigo_factura INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(codigo_factura) REFERENCES FACTURA(codigo),
FOREIGN KEY(codigo_producto) REFERENCES PRODUCTO(codigo)
);

CREATE TABLE IF NOT EXISTS PEDIDO(
codigo INT NOT NULL AUTO_INCREMENT,
fecha DATE NOT NULL,
cantidad INT NOT NULL,
total DOUBLE NOT NULL,
anticipo DOUBLE NOT NULL,
codigo_producto VARCHAR(45) NOT NULL,
nit_cliente VARCHAR(13) NOT NULL,
codigo_tienda_destino VARCHAR(45) NOT NULL,
codigo_tienda_origen VARCHAR(45) NOT NULL,
PRIMARY KEY(codigo),
FOREIGN KEY(codigo_producto) REFERENCES PRODUCTO(codigo),
FOREIGN KEY(nit_cliente) REFERENCES CLIENTE(NIT),
FOREIGN KEY(codigo_tienda_origen) REFERENCES TIENDA(codigo),
FOREIGN KEY(codigo_tienda_destino) REFERENCES TIENDA(codigo)
);

CREATE TABLE IF NOT EXISTS RECIBE(
ID INT NOT NULL AUTO_INCREMENT,
fecha_entrega DATE NOT NULL,
codigo_tienda VARCHAR(45) NOT NULL,
codigo_pedido INT NOT NULL,
codigo_tiempo_de_envio INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(codigo_tienda) REFERENCES TIENDA(codigo),
FOREIGN KEY(codigo_pedido) REFERENCES PEDIDO(codigo),
FOREIGN KEY(codigo_tiempo_de_envio) REFERENCES TIEMPO_DE_ENVIO(ID)
);




