/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import conexionDB.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author jalej
 */
public class CrearEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form CrearEmpleado
     */
    public CrearEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        codigo_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        telefono_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        direccion_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nit_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        email_txt = new javax.swing.JTextField();
        dpi_txt = new javax.swing.JTextField();
        nombre_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 180, -1, 30));

        codigo_txt.setBackground(new java.awt.Color(255, 255, 255));
        codigo_txt.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        codigo_txt.setForeground(new java.awt.Color(0, 0, 0));
        codigo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_txtActionPerformed(evt);
            }
        });
        jPanel1.add(codigo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 230, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresar nuevo empleado.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Telefono:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 250, -1, 30));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIT:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 320, -1, 30));

        telefono_txt.setBackground(new java.awt.Color(255, 255, 255));
        telefono_txt.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        telefono_txt.setForeground(new java.awt.Color(0, 0, 0));
        telefono_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefono_txtKeyTyped(evt);
            }
        });
        jPanel1.add(telefono_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 230, 30));

        jLabel9.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DPI:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 110, -1, 30));

        direccion_txt.setBackground(new java.awt.Color(255, 255, 255));
        direccion_txt.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        direccion_txt.setForeground(new java.awt.Color(0, 0, 0));
        direccion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_txtActionPerformed(evt);
            }
        });
        jPanel1.add(direccion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 250, 230, 30));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Direccion:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 250, -1, 30));

        jLabel12.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 180, -1, 30));

        nit_txt.setBackground(new java.awt.Color(255, 255, 255));
        nit_txt.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        nit_txt.setForeground(new java.awt.Color(0, 0, 0));
        nit_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nit_txtKeyTyped(evt);
            }
        });
        jPanel1.add(nit_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 230, 30));

        jLabel8.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Codigo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 110, -1, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargar (1).png"))); // NOI18N
        jButton1.setText("Cargar");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 280, 40));

        email_txt.setBackground(new java.awt.Color(255, 255, 255));
        email_txt.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        email_txt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 180, 230, 30));

        dpi_txt.setBackground(new java.awt.Color(255, 255, 255));
        dpi_txt.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        dpi_txt.setForeground(new java.awt.Color(0, 0, 0));
        dpi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpi_txtActionPerformed(evt);
            }
        });
        dpi_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dpi_txtKeyTyped(evt);
            }
        });
        jPanel1.add(dpi_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 110, 230, 30));

        nombre_txt.setBackground(new java.awt.Color(255, 255, 255));
        nombre_txt.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        nombre_txt.setForeground(new java.awt.Color(0, 0, 0));
        nombre_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_txtKeyTyped(evt);
            }
        });
        jPanel1.add(nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 230, 30));

        jLabel13.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("*");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 110, 30, -1));

        jLabel14.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("*");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 250, 20, -1));

        jLabel17.setFont(new java.awt.Font("Leelawadee", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("* Campos Obligatorios");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 140, 20));

        jLabel15.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 20, -1));

        jLabel16.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("*");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 20, -1));

        jLabel18.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("*");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 20, -1));

        jLabel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255), null, new java.awt.Color(153, 153, 153)));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 330, 50));

        jLabel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255), null, new java.awt.Color(153, 153, 153)));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 730, 210));

        jLabel19.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("*");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 180, 20, -1));

        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 407, 285, 45));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jButton8.setText("Regresar");
        jButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoempresa(2).jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_txtActionPerformed

    private void nombre_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_txtKeyTyped
       char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z')&& (c<' '||c>' ')) evt.consume();
    }//GEN-LAST:event_nombre_txtKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if ((codigo_txt.getText().equals("")) || (nombre_txt.getText().equals("")) || (direccion_txt.getText().equals("")) || (telefono_txt.getText().equals("")) || (email_txt.getText().equals("")) || (dpi_txt.getText().equals(""))) {
            
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos obligatorios \n","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            codigo_txt.requestFocus();
        }else if((telefono_txt.getText().length()< 8)){
            JOptionPane.showMessageDialog(null,"El número de telefono debe contener 8 digitos");
        }else if((dpi_txt.getText().length()< 13)){
            JOptionPane.showMessageDialog(null,"El número de DPI esta incompleto");
        }
        else {
            System.out.println("entra");
            insertDB(codigo_txt.getText(),nombre_txt.getText(),telefono_txt.getText(),nit_txt.getText(),dpi_txt.getText(),email_txt.getText(),direccion_txt.getText());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void telefono_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono_txtKeyTyped
        char c = evt.getKeyChar();
        if (telefono_txt.getText().length()== 8) evt.consume();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_telefono_txtKeyTyped

    private void dpi_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dpi_txtKeyTyped
       char c = evt.getKeyChar();
       if (dpi_txt.getText().length()== 13) evt.consume();
       if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_dpi_txtKeyTyped

    private void dpi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpi_txtActionPerformed

    private void nit_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nit_txtKeyTyped
         if (nit_txt.getText().length()== 13) evt.consume();
    }//GEN-LAST:event_nit_txtKeyTyped

    private void direccion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_txtActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        IngresarDatos a = new IngresarDatos();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEmpleado().setVisible(true);
            }
        });
    }
    
    public void insertDB(String cadena1,String cadena2,String cadena3,String cadena4,String cadena5,String cadena6,String cadena7){
        try {
             String query = ("INSERT INTO EMPLEADO VALUES('"+cadena1+"','"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"','"+cadena6+"','"+cadena7+"')");
             Conexion c = new Conexion();
             c.Insertar(query);
             System.out.println("Los valores han sido agregados a la base de datos ");
            vaciar();
             //c.conexionDB();
             //stmt = c.getConnection().createStatement(); 
            // stmt.executeUpdate("INSERT INTO TIENDA VALUES('"+cadena1+"','"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"','"+cadena6+"','"+cadena7+"')");
        }catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Error "+e);
         
        }
    }
      public void vaciar(){
        codigo_txt.setText(null);
        nombre_txt.setText(null);
        direccion_txt.setText(null);
        telefono_txt.setText(null);
        nit_txt.setText(null);
        dpi_txt.setText(null);
        email_txt.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo_txt;
    private javax.swing.JTextField direccion_txt;
    private javax.swing.JTextField dpi_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nit_txt;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JTextField telefono_txt;
    // End of variables declaration//GEN-END:variables
}
